INSERT INTO ingredients (name) VALUES ('Salt');
INSERT INTO ingredients (name) VALUES ('Olive oil');
INSERT INTO ingredients (name) VALUES ('Garlic');
INSERT INTO ingredients (name) VALUES ('Onion');
INSERT INTO ingredients (name) VALUES ('Tomato');
INSERT INTO ingredients (name) VALUES ('Chicken');
INSERT INTO ingredients (name) VALUES ('Lemon');
INSERT INTO ingredients (name) VALUES ('Sugar');
INSERT INTO ingredients (name) VALUES ('Flour');
INSERT INTO ingredients (name) VALUES ('Eggs');
INSERT INTO ingredients (name) VALUES ('Milk');
INSERT INTO ingredients (name) VALUES ('Butter');
INSERT INTO ingredients (name) VALUES ('Beef');
INSERT INTO ingredients (name) VALUES ('Pork');
INSERT INTO ingredients (name) VALUES ('Carrot');
INSERT INTO ingredients (name) VALUES ('Potato');
INSERT INTO ingredients (name) VALUES ('Cheese');
INSERT INTO ingredients (name) VALUES ('Lemon');
INSERT INTO ingredients (name) VALUES ('Vinegar');
INSERT INTO ingredients (name) VALUES ('Black Pepper');
INSERT INTO ingredients (name) VALUES ('Basil');
INSERT INTO ingredients (name) VALUES ('Oregano');
INSERT INTO ingredients (name) VALUES ('Cinnamon');
INSERT INTO ingredients (name) VALUES ('Vanilla');
INSERT INTO ingredients (name) VALUES ('Honey');
INSERT INTO ingredients (name) VALUES ('Rice');
INSERT INTO ingredients (name) VALUES ('Pasta');
INSERT INTO ingredients (name) VALUES ('Bread');
INSERT INTO ingredients (name) VALUES ('Yeast');
INSERT INTO ingredients (name) VALUES ('Cocoa Powder');
INSERT INTO ingredients (name) VALUES ('Baking Soda');
INSERT INTO ingredients (name) VALUES ('Baking Powder');
INSERT INTO ingredients (name) VALUES ('Nutmeg');
INSERT INTO ingredients (name) VALUES ('Paprika');
INSERT INTO ingredients (name) VALUES ('Chili Powder');
INSERT INTO ingredients (name) VALUES ('Cumin');
INSERT INTO ingredients (name) VALUES ('Curry');
INSERT INTO ingredients (name) VALUES ('Soy Sauce');
INSERT INTO ingredients (name) VALUES ('Tuna');
INSERT INTO ingredients (name) VALUES ('Shrimp');
INSERT INTO ingredients (name) VALUES ('Salmon');
INSERT INTO ingredients (name) VALUES ('Mushrooms');
INSERT INTO ingredients (name) VALUES ('Spinach');
INSERT INTO ingredients (name) VALUES ('Broccoli');
INSERT INTO ingredients (name) VALUES ('Cauliflower');
INSERT INTO ingredients (name) VALUES ('Bell Pepper');
INSERT INTO ingredients (name) VALUES ('Zucchini');
INSERT INTO ingredients (name) VALUES ('Eggplant');
INSERT INTO ingredients (name) VALUES ('Avocado');
INSERT INTO ingredients (name) VALUES ('Peas');
INSERT INTO ingredients (name) VALUES ('Corn');
INSERT INTO ingredients (name) VALUES ('Lettuce');
INSERT INTO ingredients (name) VALUES ('Cabbage');
INSERT INTO ingredients (name) VALUES ('Celery');
INSERT INTO ingredients (name) VALUES ('Radish');
INSERT INTO ingredients (name) VALUES ('Pumpkin');
INSERT INTO ingredients (name) VALUES ('Squash');
INSERT INTO ingredients (name) VALUES ('Asparagus');
INSERT INTO ingredients (name) VALUES ('Green Beans');
INSERT INTO ingredients (name) VALUES ('Artichoke');
INSERT INTO ingredients (name) VALUES ('Olives');
INSERT INTO ingredients (name) VALUES ('Coleslaw');
INSERT INTO ingredients (name) VALUES ('Sauerkraut');
INSERT INTO ingredients (name) VALUES ('Pickles');
INSERT INTO ingredients (name) VALUES ('Mustard');
INSERT INTO ingredients (name) VALUES ('Ketchup');
INSERT INTO ingredients (name) VALUES ('Mayonnaise');
INSERT INTO ingredients (name) VALUES ('Barbecue Sauce');
INSERT INTO ingredients (name) VALUES ('Hot Sauce');
INSERT INTO ingredients (name) VALUES ('Worcestershire Sauce');
INSERT INTO ingredients (name) VALUES ('Fish Sauce');
INSERT INTO ingredients (name) VALUES ('Sesame Oil');
INSERT INTO ingredients (name) VALUES ('Peanut Butter');
INSERT INTO ingredients (name) VALUES ('Almonds');
INSERT INTO ingredients (name) VALUES ('Walnuts');
INSERT INTO ingredients (name) VALUES ('Pecans');
INSERT INTO ingredients (name) VALUES ('Cashews');
INSERT INTO ingredients (name) VALUES ('Hazelnuts');
INSERT INTO ingredients (name) VALUES ('Pistachios');
INSERT INTO ingredients (name) VALUES ('Sunflower Seeds');
INSERT INTO ingredients (name) VALUES ('Pumpkin Seeds');
INSERT INTO ingredients (name) VALUES ('Chia Seeds');
INSERT INTO ingredients (name) VALUES ('Flaxseeds');
INSERT INTO ingredients (name) VALUES ('Sesame Seeds');
INSERT INTO ingredients (name) VALUES ('Coconut');
INSERT INTO ingredients (name) VALUES ('Coconut Milk');
INSERT INTO ingredients (name) VALUES ('Coconut Oil');
INSERT INTO ingredients (name) VALUES ('Maple Syrup');
INSERT INTO ingredients (name) VALUES ('Agave Syrup');
INSERT INTO ingredients (name) VALUES ('Cornstarch');
INSERT INTO ingredients (name) VALUES ('Gelatin');
INSERT INTO ingredients (name) VALUES ('Heavy Cream');
INSERT INTO ingredients (name) VALUES ('Sour Cream');
INSERT INTO ingredients (name) VALUES ('Cream Cheese');
INSERT INTO ingredients (name) VALUES ('Ricotta Cheese');
INSERT INTO ingredients (name) VALUES ('Feta Cheese');
INSERT INTO ingredients (name) VALUES ('Parmesan Cheese');
INSERT INTO ingredients (name) VALUES ('Blue Cheese');
INSERT INTO ingredients (name) VALUES ('Goat Cheese');
INSERT INTO ingredients (name) VALUES ('Tofu');
INSERT INTO ingredients (name) VALUES ('Brie Cheese');
INSERT INTO ingredients (name) VALUES ('Gruyere Cheese');
INSERT INTO ingredients (name) VALUES ('Swiss Cheese');
INSERT INTO ingredients (name) VALUES ('Provolone Cheese');
INSERT INTO ingredients (name) VALUES ('Mozzarella Cheese');
INSERT INTO ingredients (name) VALUES ('Cheddar Cheese');
INSERT INTO ingredients (name) VALUES ('Yogurt');
INSERT INTO ingredients (name) VALUES ('Ice Cream');




